ciabot: Fix str vs. int comparison.
    Traceback (most recent call last):
      […]
      File "/srv/ciabot/prod/libreoffice-bugzilla2.py", line 142, in find_target_version
        if max(beta_list) >= 2:
    TypeError: '>=' not supported between instances of 'str' and 'int'

Regression from f2204d126c2334ccbe061cd27d519316426448c1.  Solved by
turning to int early for bug numbers and maj/min/etc version numbers.